name: github_readme_beautifier
description: A web app to beautify and enhance your Github README file, that provides pictures in PNG and GIF(animated) formats.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  responsive_builder: ^0.7.0
  get: ^4.6.6
  cupertino_icons: ^1.0.2
  flutter_3d_controller: ^1.2.0
  common_utilities: ^0.1.1
  js: ^0.6.7
  ffmpeg_wasm: ^1.0.1
  responsive_framework: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0





flutter:

  uses-material-design: true

  assets:
    - assets/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
